{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "silly-helm.fullname" . }}-read-secrets-global
subjects:
  - kind: ServiceAccount
    name: {{ template "silly-helm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "silly-helm.fullname" . }}--reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
