---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sillys.ediri.io
spec:
  group: ediri.io
  names:
    categories:
      - silly-helm
    kind: Silly
    listKind: SillyList
    plural: sillys
    shortNames:
      - si
    singular: silly
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.name
          name: NAME
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: Silly is just a silly CRD
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                       of an object. Servers should convert recognized schemas to the latest
                       internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                       object represents. Servers may infer this from the endpoint the client
                       submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: SillySpec defines the desired state of Silly
              properties:
                name:
                  description: Name is the name of the silly
                  type: string
                  maxLength: 128
              required:
                - name
              type: object
            status:
              description: SillyStatus defines the observed state of Silly
              properties:
                  message:
                    description: Message is the message of the silly
                    type: string
                    maxLength: 128
              required:
                  - message
              type: object
          type: object
      served: true
      storage: true
      subresources:
          status: {}

